name: codecrafters-shell
version: 0.1.0.0
license: BSD3

dependencies:
  - base >= 4.19 && < 5
  - process
  - directory
  - filepath
  - mtl
  - containers
  - transformers
  - hspec
  - hspec-contrib
  - QuickCheck
  - HUnit
  - megaparsec
  - parser-combinators
  - text

executables:
  codecrafters-shell-exe:
    main: Main.hs
    source-dirs:
      - app
      - src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    language: GHC2021

tests:
  codecrafters-shell-test:
    main: Spec.hs
    source-dirs:
      - test
      - src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    language: GHC2021